# Permalinks
permalink: /:categories/:title/
# Setup
title:               Donde la cocina nos lleve
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
