# Permalinks
permalink: /:categories/:title/
# Setup
title: "Donde la cocina nos lleve"
description: "Blog de cocina de Bernardo I. García de la Torre y Teresa Hidalgo"
lang: "es_ES"
paginate: 5
baseurl: ""

url: "https://donde-la-cocina-nos-lleve.github.io"
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Plugins:
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-slate
