# Permalinks
permalink: /:title/
# Setup
title: "Donde la cocina nos lleve"
description: "Blog de cocina de Bernardo I. García de la Torre y Teresa Hidalgo"
lang: "es_ES"
paginate: 15
baseurl: ""

url: "https://donde-la-cocina-nos-lleve.github.io"
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Authors:
bernardo:
  name: Bernardo I. García de la Torre
  image: /assets/authors/bernardo.jpg
teresa:
  name: Teresa Hidalgo Gutiérrez
  image: /assets/authors/teresa.jpg

# Categories:
collections:
  category:
    output: true


# Staticman:
repository: "donde-la-cocina-nos-lleve/donde-la-cocina-nos-lleve.github.io"
staticman:
  branch: "master"

# Plugins:
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-slate
