backend:
  name: github
  repo: donde-la-cocina-nos-lleve/donde-la-cocina-nos-lleve.github.io
  branch: master
  site_domain: blissful-curran-bb1ffb.netlify.com

media_folder: "assets/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: "Imagen", name: "thumbnail", widget: "image"}
      - {
          label: 'Categoría',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          displayFields: [title],
          searchFields: [title],
          valueField: 'title',
          multiple: true
        }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'categories'
    label: 'Categoría'
    folder: '_category/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'category' }
      - { label: 'Short Name', name: 'tag', widget: 'string' }
      - { label: 'Titulo', name: 'title', widget: 'string' }
